language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose
    

script:
  - nosetests --with-coverage --cover-erase --cover-package=project

after_success:
  - coveralls;
